'use strict';(function($$$$){XLGames.namespace("XLGames.Wiki");XLGames.Wiki.Editor=Class.extend({init:function($$editorForm$$,$useCategory$$,$useAjaxForm$$){this.$editorForm=$$editorForm$$;this.$textarea=$$$$("textarea",this.$editorForm);this.changed=!1;this.originalText=this.getContent();this.useCategory=$useCategory$$;this.useAjaxForm=$useAjaxForm$$||!1;this.template=null},configureEditor:function($$previewBtn_editorConfig_groupCode$$){$$previewBtn_editorConfig_groupCode$$=XLGames.Wiki.createConfig({attachmentCategory:"BOARD",
previewAutoRefresh:!0,previewInElement:".wikipreview .doc",previewParserPath:"/wikis/preview",attachmentGroupCode:$$previewBtn_editorConfig_groupCode$$});this.$textarea.markItUp($$previewBtn_editorConfig_groupCode$$);void 0!=this.useCategory&&1==this.useCategory&&this.setCategory();this.bindForm();this.bindConfirmLeaving();this.bindCancelButton();this.bindHelp();this.$textarea.focus();$$previewBtn_editorConfig_groupCode$$=$$$$(".previewBtn").find("a");$$previewBtn_editorConfig_groupCode$$.trigger("mouseup");
$$previewBtn_editorConfig_groupCode$$.hide();return this},setCategory:function(){this.categoryOption={rules:{category:{required:!0}},messages:{category:{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.MultiBoard.requireCategory()}}};$$$$("#category").on("change",function(){$$$$(this).valid()})},setTemplate:function($s$$){this.template=$s$$;""==this.getContent()&&(this.originalText=this.template,this.setContent(this.template));return this},bindForm:function(){var $me$$=this,$$submitButton$$=$$$$("button[type\x3d'submit']",
$me$$.$editorForm),$options$jscomp$0$$={rules:{title:{required:!0,rangelength:[2,90]},contents:{required:!0,rangelength:[5,2E4]}},messages:{title:{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.MultiBoard.requireTitle(2,90),rangelength:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.MultiBoard.requireTitle(2,90)},contents:{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.MultiBoard.requireContents(5,2E4),rangelength:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.MultiBoard.requireContents(5,2E4)}},ignore:".ignore"};$me$$.$editorForm.validate($$$$.extend(!0,
$options$jscomp$0$$,$me$$.categoryOption));$$submitButton$$.click(function($e$$){$e$$.preventDefault();$me$$.unbindConfirmLeaving();if($me$$.useAjaxForm){if($me$$.isTemplateContent())return 0==$$$$('label[for\x3d"content"]').length&&($e$$='\x3clabel for\x3d"content" class\x3d"error"\x3e '+XLGames.DEFAULT_ERROR_MARK.mark+AL10N.MultiBoard.requireContents()+"\x3c/label\x3e",$$$$($e$$).insertAfter("#contents")),!1;$me$$.$editorForm.valid()&&$me$$.$editorForm.ajaxSubmit({type:"post",dataType:"text",beforeSerialize:function($$f$$,
$options$$){},success:function($data$jscomp$79_emsg$$){"true"==$data$jscomp$79_emsg$$?-1<location.href.indexOf("/promotions/2015/housingcontest")?location.href="/promotions/2015/housingcontest/list":location.reload():"no_image"==$data$jscomp$79_emsg$$?($data$jscomp$79_emsg$$='\x3clabel class\x3d"error"\x3e '+XLGames.DEFAULT_ERROR_MARK.mark+AL10N.MultiBoard.requirePcImageUpload()+"\x3c/label\x3e",$$$$($data$jscomp$79_emsg$$).insertAfter("#contents")):XLGames.alert(XLGames.DEFAULT_ERROR_MESSAGE)}})}else $me$$.$editorForm.submit()})},
bindCancelButton:function(){var $me$$=this;$$$$(".btn_cancel",$me$$.$editorForm).bind("click",function(){XLGames.confirm(AL10N.Global.confirmCancel(),function(){$me$$.unbindConfirmLeaving();history.go(-1)},function(){return!1},AL10N.Button.ok(),AL10N.Button.cancel());return!1})},bindHelp:function(){$$$$(".open_window",this.$editForm).openWindow()},isTemplateContent:function(){return null!=this.template?this.template==this.getContent():!1},isChanged:function(){return null!=this.template?this.originalText!=
this.getContent():this.template!=this.getContent()},getContent:function(){return this.$textarea.val()},setContent:function($s$$){this.$textarea.val($s$$)},bindConfirmLeaving:function(){var $me$$=this;$$$$(window).on("beforeunload",function($e$$){if($me$$.isChanged()){if($e$$=$e$$||window.event)$e$$.returnValue=AL10N.Global.confirmLeaving();return AL10N.Global.confirmLeaving()}})},unbindConfirmLeaving:function(){$$$$(window).unbind("beforeunload")}})})(jQuery);
(function($$$$){$$$$.extend($$$$.fn,{validateDelegate:function($delegate$$,$type$$,$handler$$){return this.bind($type$$,function($event$$){var $target$$=$$$$($event$$.target);if($target$$.is($delegate$$))return 0<=arguments[0].target.getAttribute("class").indexOf("ignore")?!1:$handler$$.apply($target$$,arguments)})}})})(jQuery);
$.extend($.validator,{staticRules:function($element$$){var $rules$$={},$validator$$=$.data($element$$.form,"validator");if(void 0!=$validator$$)return $validator$$.settings.rules&&($rules$$=$.validator.normalizeRule($validator$$.settings.rules[$element$$.name])||{}),$rules$$}});