'use strict';(function(){XLGames.namespace("XLGames.Member.Update");XLGames.Member.Update.Form=Class.extend({init:function($$form$$){this.$form=$$form$$;this.$confirmBtn=$("#confirmBtn",$$form$$);this.validateOptions=this._rules();this._addValidate()},_addValidate:function(){if(void 0!=$.validator&&0!=$("#emailId").length){this.validateOptions.groups.email="email.id email.domain";var $am$$={"email.id":{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.requiredEmail()},"email.domain":{required:XLGames.DEFAULT_ERROR_MARK.mark+
AL10N.Member.requiredEmail(),validateEmail:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.invalidEmailFormat()}};$.extend(this.validateOptions.rules,{"email.id":{required:!0},"email.domain":{required:!0,validateEmail:"#emailId"}});$.extend(this.validateOptions.messages,$am$$)}},getValidateOptions:function(){return this.validateOptions},_rules:function(){return{ignore:"",onkeyup:!1,groups:{phoneNo:"phone.firstNo phone.secondNo phone.thirdNo phone.isSmsReceiveAgreement phone.isPhoneCertification"},rules:{"phone.firstNo":{required:function(){return""!=
$("#phoneFirstNo").val()||""!=$("#phoneSecondNo").val()||""!=$("#phoneThirdNo").val()},firstMobilePhoneNo:function(){return""!=$("#phoneFirstNo").val()||""!=$("#phoneSecondNo").val()||""!=$("#phoneThirdNo").val()},phone:function($elem$$){$("#phone_auth_msg").empty();return[$("#phoneFirstNo").val(),$("#phoneSecondNo").val(),$("#phoneThirdNo").val()]}},"phone.secondNo":{required:function(){return""!=$("#phoneFirstNo").val()||""!=$("#phoneSecondNo").val()||""!=$("#phoneThirdNo").val()},phone:function(){$("#phone_auth_msg").empty();
return[$("#phoneFirstNo").val(),$("#phoneSecondNo").val(),$("#phoneThirdNo").val()]}},"phone.thirdNo":{required:function(){return""!=$("#phoneFirstNo").val()||""!=$("#phoneSecondNo").val()||""!=$("#phoneThirdNo").val()},phone:function(){$("#phone_auth_msg").empty();return[$("#phoneFirstNo").val(),$("#phoneSecondNo").val(),$("#phoneThirdNo").val()]}},"phone.isSmsReceiveAgreement":{required:function(){return 1==$("input:checkbox[id\x3dphoneCheck]").is(":checked")&&""==$("#phoneFirstNo").val()&&""==
$("#phoneSecondNo").val()&&""==$("#phoneThirdNo").val()},checkSmsAgreement:function(){$("#phone_auth_msg").empty();return[$("#phoneFirstNo").val(),$("#phoneSecondNo").val(),$("#phoneThirdNo").val()]}},"phone.isPhoneCertification":{required:function(){return""!=$("#phoneFirstNo").val()||""!=$("#phoneSecondNo").val()||""!=$("#phoneThirdNo").val()},phoneAuth:function(){$("#phone_auth_msg").empty();return[$("#phoneFirstNo").val(),$("#phoneSecondNo").val(),$("#phoneThirdNo").val()]}}},messages:{"phone.firstNo":{required:XLGames.DEFAULT_ERROR_MARK.mark+
AL10N.Member.requiredMobilePhoneNo(),firstMobilePhoneNo:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.invalidFirstMobilePhoneNo(),phone:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.invalidFirstMobilePhoneNo()},"phone.secondNo":{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.requiredMobilePhoneNo(),phone:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.invalidFirstMobilePhoneNo()},"phone.thirdNo":{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.requiredMobilePhoneNo(),phone:XLGames.DEFAULT_ERROR_MARK.mark+
AL10N.Member.invalidFirstMobilePhoneNo()},"phone.isSmsReceiveAgreement":{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.requiredMobilePhoneNo(),checkSmsAgreement:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.requiredMobilePhoneNo()},"phone.isPhoneCertification":{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.needPhoneAuthCheck(),phoneAuth:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.needPhoneAuthCheck()}},errorPlacement:function($error$$,$element$$){XLGames.DEFAULT_ERROR_PLACE.errorPlacement($error$$,
$element$$)}}}});XLGames.Member.Update.TransIdAgreement=Class.extend({init:function($$form$$){this.$form=$$form$$;this.$confirmBtn=$("#confirmBtn",$$form$$)},rules:function(){return{ignore:"",onkeyup:!1,rules:{userAgree:{required:!0},personalAgree:{required:!0}},messages:{userAgree:{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.confirmUserAgree()},personalAgree:{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.confirmPersonalAgree()}},errorPlacement:function($error$$,$element$$){XLGames.DEFAULT_ERROR_PLACE.errorPlacement($error$$,
$element$$)}}}});XLGames.Member.Update.TransIdForm=Class.extend({init:function($$form$$){this.$form=$$form$$;this.$confirmBtn=$("#confirmBtn",$$form$$);this.addValidate()},failureProcess:function($jqXHR_msgs$$){var $message$$=AL10N.Global.tryagain();if(403==$jqXHR_msgs$$.status&&void 0!=$jqXHR_msgs$$.getResponseHeader("messageKeys")){$jqXHR_msgs$$=$jqXHR_msgs$$.getResponseHeader("messageKeys").split(",");for(var $a$$ in $jqXHR_msgs$$)$message$$+=XLGames.executeFunctionByName($jqXHR_msgs$$[$a$$],window)+
"\n"}else $message$$=$.parseJSON($jqXHR_msgs$$.responseText).message,$message$$=$message$$.replace("\x3cbr /\x3e","\n");$(window).unbind("beforeunload");XLGames.alert($message$$,function(){location.href="/user/transid"})},addValidate:function(){var $me$$=this;void 0!=$.validator&&$.validator.addMethod("validateEmailId",function($emailAddress_value$$,$element$$,$param$$){var $validator$$=this;if($me$$.$confirmBtn.data("isRegister"))return!0;$emailAddress_value$$=$($param$$).val();$.ajax({type:"POST",
url:"/user/transid/validateEmailId",data:{id:$emailAddress_value$$},success:function($errorMessage_response$$){var $errors$$={};if(null==$errorMessage_response$$||void 0==$errorMessage_response$$)$errorMessage_response$$=AL10N.Global.accessDenied();else{if($errorMessage_response$$.result)return!0;$errorMessage_response$$=$errorMessage_response$$.errorMessage}$errors$$[$element$$.name]=XLGames.DEFAULT_ERROR_MARK.mark+$errorMessage_response$$;$validator$$.showErrors($errors$$);return!1},error:function($jqXHR$$,
$textStatus$$,$errorThrown$$){$me$$.failureProcess($jqXHR$$);return!1},dataType:"json",async:!1});return!0})},rules:function(){var $me$$=this;return{ignore:"",onkeyup:!1,submitHandler:function($form$$){if($me$$.$confirmBtn.data("isRegister"))return!1;$me$$.$confirmBtn.html(AL10N.Btn.inprogress);$me$$.$confirmBtn.data("isRegister","true");$form$$.submit()},rules:{id:{required:!0,validateFullEmail:"#id",validateEmailId:"#id"}},messages:{id:{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.requiredEmail(),
validateFullEmail:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.invalidEmailFormat()}},errorPlacement:function($error$$,$element$$){XLGames.DEFAULT_ERROR_PLACE.errorPlacement($error$$,$element$$)}}}});XLGames.Member.Update.ChangePassword=Class.extend({init:function($$form$$){this.$form=$$form$$;this.$confirmBtn=$("#confirmBtn",$$form$$)},rules:function(){return{onkeyup:!1,onfocusout:!1,rules:{password:{required:!0,minlength:8,maxlength:16,validateLoginPassword:"#password"},confirmPassword:{required:!0,
passwordConfirm:"#password"}},messages:{password:{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.requiredPassword(),minlength:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.invalidPasswordFormat(),maxlength:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.invalidPasswordFormat()},confirmPassword:{required:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.requiredPassword(),passwordConfirm:XLGames.DEFAULT_ERROR_MARK.mark+AL10N.Member.confirmPassword()}},errorPlacement:function($error$$,$element$$){XLGames.DEFAULT_ERROR_PLACE.errorPlacement($error$$,
$element$$)}}}})})(jQuery);