'use strict';(function($$$$){function $escapeHtml$$($escaped$jscomp$2_str$$){if(null===$escaped$jscomp$2_str$$||0===$escaped$jscomp$2_str$$.length)return"";$escaped$jscomp$2_str$$=$escaped$jscomp$2_str$$.replace(/&/g,"\x26amp;");$escaped$jscomp$2_str$$=$escaped$jscomp$2_str$$.replace(/</g,"\x26lt;");$escaped$jscomp$2_str$$=$escaped$jscomp$2_str$$.replace(/>/g,"\x26gt;");$escaped$jscomp$2_str$$=$escaped$jscomp$2_str$$.replace(/"/g,"\x26quot;");return $escaped$jscomp$2_str$$=$escaped$jscomp$2_str$$.replace(/'/g,
"\x26#39;")}"undefined"===typeof window.XLGames&&(window.XLGames={});XLGames.namespace=function($ns_parts$$){$ns_parts$$=$ns_parts$$.split(".");var $parent$$=XLGames,$i$$;"XLGames"===$ns_parts$$[0]&&($ns_parts$$=$ns_parts$$.slice(1));for($i$$=0;$i$$<$ns_parts$$.length;$i$$+=1)"undefined"===typeof $parent$$[$ns_parts$$[$i$$]]&&($parent$$[$ns_parts$$[$i$$]]={}),$parent$$=$parent$$[$ns_parts$$[$i$$]];return $parent$$};XLGames.namespace("XLGames");XLGames.Localization={message:function($text$$){return function(){var $args$$=
[$text$$];$args$$=$args$$.concat(Array.prototype.slice.apply(arguments));return XLGames.Localization.format.apply(null,$args$$)}},format:function($text$$){var $token$$;if(1>=arguments.length)return $text$$;var $tokenCount$$=arguments.length-2;for($token$$=0;$token$$<=$tokenCount$$;$token$$+=1)$text$$=$text$$.replace(new RegExp("\\{"+$token$$+"\\}","gi"),arguments[$token$$+1]);return $text$$}};window.AL10N={};XLGames.DEFAULT_ERROR_MARK={mark:""};XLGames.DEFAULT_ERROR_PLACE={errorPlacement:function($error$$,
$element$$){XLGames.DEFAULT_ERROR_PLACE.findCautionElement($element$$).html($error$$)},findCautionElement:function($$inputElement$$){var $cautionElement$$=$cautionElement$$=$$inputElement$$.nextAll("div[class\x3d'caution']:first");0===$cautionElement$$.length&&($cautionElement$$=$$inputElement$$.parent().nextAll("div[class\x3d'caution']:first"));0===$cautionElement$$.length&&($cautionElement$$=$$inputElement$$.parents().nextAll("div[class\x3d'caution']:first"));return $cautionElement$$}};XLGames.Url=
{img:function($imgPath$$){if(!$imgPath$$)return console.log("imgPath is Empty!!"),"";0!=$imgPath$$.indexOf("/")&&($imgPath$$="/"+$imgPath$$);return XLGames.imgPrefix+$imgPath$$}};XLGames.executeFunctionByName=function($functionName$$,$context$$){for(var $args$$=Array.prototype.slice.call(arguments).splice(2),$namespaces$$=$functionName$$.split("."),$func$$=$namespaces$$.pop(),$i$$=0;$i$$<$namespaces$$.length;$i$$++)$context$$=$context$$[$namespaces$$[$i$$]];return $context$$[$func$$].apply(this,$args$$)};
var $token$jscomp$0$$=$$$$("meta[name\x3d'_csrf']").attr("content"),$header$$=$$$$("meta[name\x3d'_csrf_header']").attr("content");$$$$(document).ajaxSend(function($e$$,$xhr$$,$options$$){$token$jscomp$0$$&&$header$$?($e$$=$options$$.url,(0==$e$$.indexOf("/")||-1<$e$$.indexOf("xlgames"))&&$xhr$$.setRequestHeader($header$$,$token$jscomp$0$$)):console.log("csrf 값을 확인해주세요")});$$$$.ajaxSetup({cache:!1,timeout:6E4,type:"post"});$$$$.fn.modalDialog=function($userOptions$$){function $doCommand$$($command_st$$){var $$modal$$=
$$me$$.parent();switch($command_st$$){case "close":$$modal$$.fadeOut("slow");break;case "open":$options$$.docBody.prop("scrollHeight")>$options$$.docBody.prop("clientHeight")&&$options$$.docBody.css("overflow-y","scroll");$options$$.docBody.width()==$options$$.docWindow.width()&&$$me$$.wrapperContent.css("width","100%");$options$$.docBody.find(":enabled").attr("disabled","disabled").addClass("__modal-disabled");$options$$.docBody.find("div.modal").removeAttr("disabled").removeClass("__modal-disabled");
$options$$.docBody.find("div.modal").find(".__modal-disabled").removeAttr("disabled").removeClass("__modal-disabled");$command_st$$=$$$$(window).scrollTop();var $sl$$=$$$$(window).scrollLeft();$$me$$.wrapperContent.addClass("pos-fixed").css("top",-$command_st$$+"px").css("left",-$sl$$+"px");$$modal$$.fadeIn("slow");$$$$(window).trigger("resize");break;case "destroy":$options$$.docBody.find(".__modal-disabled").removeAttr("disabled").removeClass("__modal-disabled"),$options$$.docBody.css("overflow-y",
""),$command_st$$=$$me$$.wrapperContent.css("top"),$command_st$$=String($command_st$$).replace("px",""),$sl$$=$$me$$.wrapperContent.css("left"),$sl$$=String($sl$$).replace("px",""),$command_st$$=Math.abs($command_st$$),$sl$$=Math.abs($sl$$),$$modal$$.fadeOut("slow").remove(),$$me$$.wrapperContent.removeClass("pos-fixed").css("top","").css("left","").css("width",""),$$$$(window).scrollTop($command_st$$).scrollLeft($sl$$)}}function $setDialogPosition$$(){var $left$$=$options$$.docWindow.width(),$windowHeight$$=
$options$$.docWindow.height();null!==$options$$.windowWidth&&null!==$options$$.windowHeight&&($left$$=$options$$.windowWidth,$windowHeight$$=$options$$.windowHeight);$$modalContainer$$.css({width:$left$$+"px",height:$windowHeight$$+"px"});var $top$$=$options$$.top;null==$options$$.top&&($top$$=($windowHeight$$-$$me$$.outerHeight())/2,0>$top$$&&($top$$=0));$left$$=($left$$-$$me$$.outerWidth())/2;0>$left$$&&($left$$=0);$$me$$.css({top:$top$$+"px",left:$left$$+"px"})}var $$me$$=this;$$me$$.wrapperContent=
$$$$("#wrapperContent");var $options$$=$$$$.extend({zIndex:1},$$$$.fn.modalDialog.defaults,$userOptions$$);if("string"===typeof $userOptions$$)$doCommand$$($userOptions$$);else{if(void 0==$options$$.docBody||0==$options$$.docBody.length)$options$$.docBody=$$$$("body");if(void 0==$options$$.docWindow||0==$options$$.docWindow.length)$options$$.docWindow=$$$$(window);var $$modalContainer$$=$$$$('\x3cdiv class\x3d"modal" /\x3e');$$me$$.css({position:"absolute","z-index":2}).data("options",$options$$).data("modalContainer",
$$modalContainer$$);$$modalContainer$$.css("z-index",$options$$.zIndex).append('\x3cdiv class\x3d"modal_bg" /\x3e').append($$me$$);$options$$.docBody.append($$modalContainer$$);$$$$(window).on("resize",$setDialogPosition$$).trigger("resize")}return $$me$$};$$$$.fn.modalDialog.defaults={zIndex:1,windowWidth:null,windowHeight:null,top:null,docBody:$$$$("body"),docWindow:$$$$(window)};$$$$.fn.openWindow=function(){this.click(function(){var $$link_features$$=$$$$(this),$url$$=$$link_features$$.attr("href"),
$windowTitle$$=$$link_features$$.attr("window-title");$$link_features$$=$$link_features$$.data("features");window.open($url$$,$windowTitle$$,$$link_features$$);return!1})};XLGames.alert=function($escaped_str$$,$okFunction$$){if(XLGames.isMobileView)return alert($escaped_str$$),$okFunction$$&&$okFunction$$(),!1;$escaped_str$$=$escapeHtml$$($escaped_str$$);$escaped_str$$=$escaped_str$$.split("\n").join("\x3cbr/\x3e");XLGames.alertHtml($escaped_str$$,$okFunction$$)};XLGames.alertHtml=function($html$$,
$okFunction$$){var $$alertMessage$$=$$$$("\x3cdiv class\x3d'layer_comm'\x3e\x3cdiv class\x3d'txt'\x3e"+$html$$+"\x3c/div\x3e\x3cdiv class\x3d'wrap_btn'\x3e\x3cbutton type\x3d'button' class\x3d'btn-ok' id\x3d'okBtn'\x3e"+AL10N.Btn.ok()+"\x3c/button\x3e\x3c/div\x3e");$$$$("body").append($$alertMessage$$);$$$$("#okBtn",$$alertMessage$$).bind("click",function(){$$alertMessage$$.modalDialog("destroy");$okFunction$$&&$okFunction$$();return!1});$$alertMessage$$.modalDialog({zIndex:5E4});$$alertMessage$$.modalDialog("open");
$$$$("#okBtn",$$alertMessage$$).focus();$$$$(".layer_comm").bind("keydown",function($e$$){27==$e$$.keyCode&&$$$$("#okBtn",$$alertMessage$$).click()})};XLGames.confirm=function($escaped$jscomp$1_str$$,$okFunction$$,$cancelFunction$$,$okButtonLabel$$,$cancelButtonLabel$$,$eventElement$$){$escaped$jscomp$1_str$$=$escapeHtml$$($escaped$jscomp$1_str$$);$escaped$jscomp$1_str$$=$escaped$jscomp$1_str$$.split("\n").join("\x3cbr/\x3e");if("undefined"===typeof $okButtonLabel$$||null===$okButtonLabel$$)$okButtonLabel$$=
AL10N.Btn.ok();if("undefined"===typeof $cancelButtonLabel$$||null===$cancelButtonLabel$$)$cancelButtonLabel$$=AL10N.Btn.cancel();var $$confirmMessage$$=$$$$("\x3cdiv class\x3d'layer_comm'\x3e\x3cdiv class\x3d'txt'\x3e"+$escaped$jscomp$1_str$$+"\x3c/div\x3e\x3cdiv class\x3d'wrap_btn'\x3e\x3cbutton type\x3d'button' class\x3d'btn-ok' id\x3d'okBtn' style\x3d'margin-right:5px;'\x3e"+$okButtonLabel$$+"\x3c/button\x3e\x3cbutton type\x3d'button' class\x3d'btn-cancel' id\x3d'cancelBtn'\x3e"+$cancelButtonLabel$$+
"\x3c/button\x3e\x3c/div\x3e");$$$$("#okBtn",$$confirmMessage$$).bind("click",function(){$$confirmMessage$$.modalDialog("destroy");"function"===typeof $okFunction$$&&("undefined"===typeof $eventElement$$||null===$eventElement$$?$okFunction$$():$okFunction$$($eventElement$$));return!1});$$$$("#cancelBtn",$$confirmMessage$$).bind("click",function(){$$confirmMessage$$.modalDialog("destroy");try{"function"===typeof $cancelFunction$$&&$cancelFunction$$()}catch($e$$){}return!1});$$$$("body").append($$confirmMessage$$);
$$confirmMessage$$.modalDialog({zIndex:5E4});$$confirmMessage$$.modalDialog("open");$$$$(".layer_comm").bind("keydown",function($e$$){27==$e$$.keyCode&&$$$$("#cancelBtn",$$confirmMessage$$).click()});$$$$("#okBtn",$$confirmMessage$$).focus()};"undefined"===typeof window.console&&(window.console={},console.log=function(){});XLGames.jsonHeader=function(){var $csrfHeader$$=$$$$("meta[name\x3d'_csrf_header']").attr("content"),$csrfValue$$=$$$$("meta[name\x3d'_csrf']").attr("content");return{Accept:"application/json",
"Content-Type":"application/json","X-Requested-With":"XMLHttpRequest",[$csrfHeader$$]:$csrfValue$$}}})(jQuery);
(function(){var $initializing$$=!1,$fnTest$$=/xyz/.test(function(){xyz})?/\b_super\b/:/.*/;window.Class=function(){};Class.extend=function($prop$$){function $Class$$(){!$initializing$$&&this.init&&this.init.apply(this,arguments)}var $_super$$=this.prototype;$initializing$$=!0;var $prototype$$=new this;$initializing$$=!1;for(var $name$jscomp$0$$ in $prop$$)$prototype$$[$name$jscomp$0$$]="function"===typeof $prop$$[$name$jscomp$0$$]&&"function"===typeof $_super$$[$name$jscomp$0$$]&&$fnTest$$.test($prop$$[$name$jscomp$0$$])?
function($name$$,$fn$$){return function(){var $tmp$$=this._super;this._super=$_super$$[$name$$];var $ret$$=$fn$$.apply(this,arguments);this._super=$tmp$$;return $ret$$}}($name$jscomp$0$$,$prop$$[$name$jscomp$0$$]):$prop$$[$name$jscomp$0$$];$Class$$.prototype=$prototype$$;$Class$$.prototype.constructor=$Class$$;$Class$$.extend=window.Class.extend;return $Class$$}})();