'use strict';
(function ($m$$) {
    AL10N.Member = {
        requiredName: $m$$("请输入姓名。"),
        invalidName: $m$$("请输入正确的姓名。"),
        requiredUsername: $m$$("请输入有效的电子邮件地址。"),
        requiredSsn: $m$$("请输入居民登记号码。"),
        requiredSsnAgree: $m$$("请同意居民登记号码的收集和使用。"),
        requiredCancelAnswer: $m$$("请输入注销理由以完成会员退出。"),
        maxlengthCancelAnswer: $m$$("最多可输入 200 个字符。"),
        requiredAnswer: $m$$("请输入答案。"),
        requiredPassword: $m$$("请输入密码。"),
        requiredCurrentPassword: $m$$("请输入当前密码。"),
        requiredNewPassword: $m$$("请输入新密码。"),
        requiredNewPasswordConfirm: $m$$("请重新输入密码。"),
        requiredEmail: $m$$("请输入电子邮件地址。"),
        confirmUserAgree: $m$$("请同意服务条款。"),
        confirmPersonalAgree: $m$$("请阅读并同意隐私政策。"),
        confirmPersonalTrustAgree: $m$$("请确认您同意我们的服务条款和隐私政策。"),
        conrirmUserAgreeAndPersonalAgree: $m$$("请进行钱包验证或手机钱包验证，以获取完整服务访问权限。"),
        requiredBirthDate: $m$$("请输入出生日期。"),
        invalidBirthDate: $m$$("请输入正确的法定出生日期。"),
        requiredConfirmPassword: $m$$("请重新输入密码。"),
        confirmPassword: $m$$("密码不匹配。"),
        confirmOldPassword: $m$$("当前密码与新密码相同。<br>请输入不同的密码。"),
        requiredCaptcha: $m$$("请勾选复选框。"),
        invalidCaptchaFormat: $m$$("请勾选复选框。"),
        invalidEmail: $m$$("请输入有效的电子邮件地址。"),
        requiredPhoneNo: $m$$("请输入联系电话。"),
        invalidPhone: $m$$("请输入正确的联系电话。"),
        invalidFirstPhoneNo: $m$$("请输入正确的联系电话。"),
        invalidFirstMobilePhoneNo: $m$$("请输入正确的手机号码。"),
        requiredMobilePhoneNo: $m$$("请输入手机号码。"),
        problemDuringMobileAuth: $m$$("认证过程中发生问题。"),
        exceedDailyPhoneAuthCount: $m$$("已超出当天认证次数。"),
        timeoutPhoneAuth: $m$$("认证时间已超时，请重试。"),
        invalidPhoneAuthNumber: $m$$("请输入有效的验证码。"),
        maxLengthPhoneAuthNumber: $m$$("请输入有效的验证码。"),
        phoneAuthNumberMismatch: $m$$("验证码不匹配。"),
        minlengthPassword: $m$$("密码必须包含 8-16 个字符，并包括数字、字母或特殊字符。"),
        maxlengthPassword: $m$$("密码必须包含 8-16 个字符，并包括数字、字母或特殊字符。"),
        invalidSsn: $m$$("请输入正确的居民登记号码。"),
        invalidUserIdFormat: $m$$("用户名必须由 4-12 个小写字母或数字组成，且不能仅由数字组成。<br />"),
        invalidUserIdAuthentification: $m$$("发生错误，请重新进行身份认证后再注册。"),
        invalidPasswordFormat: $m$$("密码必须包含 8-16 个字符，并包括数字、字母或特殊字符。"),
        invalidEmailFormat: $m$$("请输入有效的电子邮件地址。"),
        invalidEmailFormatAuth: $m$$("该电子邮件地址已被使用。"),
        sentAuthMail: $m$$("要完成验证并注册，请在 24 小时内点击验证邮件中的链接。"),
        sentFirstAuthMail: $m$$("创建账户后，验证邮件将发送到输入的电子邮件地址。<br>验证邮件可在 24 小时内进行验证。"),
        invalidAnswerInput: $m$$("身份验证答案最多可输入 10 个字符。"),
        requiredAuthAnswer: $m$$("请输入身份验证答案。"),
        requiredAuthQuestion: $m$$("请输入身份验证问题。"),
        invalidAuthQuestionFormat: $m$$("请输入 2~12 个字符的身份验证问题。"),
        notAuthenticatedEmail: $m$$("该账户未在会员信息中完成电子邮件验证。"),
        failIdentification: $m$$("错误代码：{0}\n请联系客户服务 1:1 咨询或拨打 1566-0550（全国通用）进行咨询。"),
        notExistedAccountId: $m$$("该账号未注册。"),
        confirmProtectorAgree: $m$$("请同意收集/使用子女的个人信息并允许其使用游戏。"),
        confirmUniqueAgree: $m$$("请同意收集和使用监护人的个人信息。"),
        requiredValidTerm: $m$$("请选择有效期。"),
        requiredCertificatePhoneNo: $m$$("请输入电话号码。"),
        requiredCertificateConfirmPhoneNo: $m$$("请确认电话号码。"),
        invalidCertificatePhoneNo: $m$$("请输入正确的电话号码。"),
        mismatchCertificatePhoneNo: $m$$("电话号码不匹配。"),
        cautionProcessStep: $m$$("离开此页面后，输入的信息不会被保存。"),
        requiredCancelConfirm: $m$$("请确认并同意上述内容。"),
        requiredAccountIds: $m$$("请选择账号。"),
        resendAuthEmail: $m$$("已重新发送验证邮件。"),
        joinResendAuthEmailFail: $m$$("重新发送验证邮件失败。\n请检查电子邮件地址是否有效。"),
        transIdResendAuthEmailFail: $m$$("重新发送验证邮件失败。\n请检查电子邮件地址是否有效。"),
        passwordByEmail: $m$$("已发送验证邮件。\n如果 24 小时内未完成验证，验证将自动撤销。"),
        invalidPasswordByEmail: $m$$("请输入有效的电子邮件地址。"),
        needPhoneAuthCheck: $m$$("请进行手机所有权认证。"),
        requiredLogout: $m$$("请先注销后再进行操作。")
    };
    AL10N.Global = {
        loginRequired: $m$$("请先登录。"),
        forbidden: $m$$("没有权限。"),
        reqCs: $m$$("请联系客户支持。"),
        accessDeniedGuardianAgreeWaitUser: $m$$("监护人未同意。"),
        accessDeniedCancelingUser: $m$$("正在申请注销会员。"),
        accessDeniedPreserveUser: $m$$("因异常访问或账户盗用嫌疑，账户已被暂时限制。"),
        accessDeniedNotCertifiedUser: $m$$("未完成身份验证。\n请在【会员信息修改】菜单中完成身份验证后使用。"),
        accessDeniedNotCertifiedOldUser: $m$$("未认证的账户，受限账户。"),
        accessDeniedStealUser: $m$$("账户因被举报为盗用而受限。"),
        accessDeniedInactive: $m$$("休眠账户。"),
        accessDenied: $m$$("没有权限。"),
        prepareOpen: $m$$("准备中。"),
        imageMaxFileSize: $m$$("图片文件最大可上传 3MB。"),
        tryagain: $m$$("请重新尝试。"),
        loginFailTrayAgain: $m$$("登录失败，请重试。"),
        defaultErrorMessage: "系统错误，请联系管理员！"
    };
    AL10N.Browser = {
        closeMsg: $m$$("我不会下载此浏览器。"),
        notSupport: $m$$("不支持的浏览器。"),
        useNewer: $m$$("请使用最新版本。")
    };
    AL10N.EmailAuth = {
        invalidAuthCode: $m$$("请输入有效的验证码。"),
        mismatchAndExpireAuthCode: $m$$("验证码有效期为 10 分钟。"),
        resendFail: $m$$("发送验证邮件失败。\n请稍后再试。"),
        resendComplete: $m$$("验证邮件已发送到请求的电子邮件地址。")
    };
    AL10N.Btn = {
        cancel: $m$$("取消"),
        deleteFile: $m$$("删除"),
        findFile: $m$$("浏览"),
        ok: $m$$("确定"),
        registering: $m$$("注册中..."),
        save: $m$$("保存"),
        emailVerification: $m$$("电子邮件验证"),
        inprogress: $m$$("进行中..."),
        authenticating: $m$$("正在认证")
    };
    AL10N.Wallet = {
        needInstall: $m$$("请安装 MetaMask。"),
        connectWallet: $m$$("请连接您的钱包。"),
        checkoutPlugin: $m$$("请检查 MetaMask 插件的当前状态。"),
        differentSender: $m$$("无效的请求。"),
        differentAddress: $m$$("已认证的地址不同"),
        exception: $m$$("发生错误，请重试。"),
        invalidNetwork: $m$$("网络无效。"),
        duplicateWallet: $m$$("该地址已被其他人使用。"),
        connectBtn: $m$$("连接钱包"),
        signMessage: $m$$("XLGAMES Global（ArcheWorld）请求认证。\n此请求不会触发区块链交易或任何付款。\n钱包地址: {0}"),
        reqAuthAddress: $m$$("钱包地址未在 XLGAMES 中验证。"),
        useBrowser: $m$$("请使用最新版本的 Chrome 或 Edge 浏览器。")
    };
    AL10N.Bora = {
        ready: $m$$("正在连接到 BORA PORTAL"),
        connected_user: $m$$("通过已经在 BORA PORTAL 上验证的用户连接"),
        connected_wallet: $m$$("通过已连接到 BORA PORTAL 的钱包连接"),
        expired: $m$$("连接超时"),
        exception: $m$$("发生错误，请重试。")
    }
})(XLGames.Localization.message);