'use strict';(function($$$$){XLGames.namespace("Game.World");XLGames.Game.World=Class.extend({init:function(){this.isEventClicked=!1;this.$navi=$$$$(".navi");this.$window=$$$$(window);this.scrollTop=this.$window.scrollTop();this.$header=$$$$("#wrap-head");this._navigation();this._countDown();this._linkBtn();this._timeLine();this.bindChangeLanguage();$$$$(window).trigger("scroll");if(""!=location.href){var $hash$$=location.hash.substring(2);$$$$(".masthead a[href\x3d'#"+$hash$$+"']").trigger("click")}},
_fixedScrolling:function(){var $me$$=this;$$$$(window).on("scroll",function(){$me$$._pageScrollActive()})},scrollAction:function($e$$){if(0<$$$$("html, body").queue("fx").length)$e$$.preventDefault();else{var $$next$$=0<$e$$.deltaY?$$$$(".navi").find("li.active").next():$$$$(".navi").find("li.active").prev();0!=$$next$$.length&&($e$$.preventDefault(),$$next$$.find("a").click())}},_navigation:function(){var $me$$=this;$me$$.$headerHeight=$$$$(".wrap-head").height();$me$$.$menuLink=$$$$(".navi-link");
$me$$.$menuLink.on({click:function($e$jscomp$8_target_top_url$$){$e$jscomp$8_target_top_url$$.preventDefault();$e$jscomp$8_target_top_url$$=$$$$(this).attr("href");if("/"!=location.pathname)return location.href="/#!"+$e$jscomp$8_target_top_url$$.substring(1),!1;$e$jscomp$8_target_top_url$$=$$$$($e$jscomp$8_target_top_url$$).offset().top-$me$$.$headerHeight;$$$$("html, body").animate({scrollTop:$e$jscomp$8_target_top_url$$},800,function(){$me$$._pageScrollActive()})}})},_pageScrollActive:function(){var $me$$=
this;$$$$(".section").each(function($idx$$,$$element_bottom$jscomp$1_elem$$){$$element_bottom$jscomp$1_elem$$=$$$$($$element_bottom$jscomp$1_elem$$);$$element_bottom$jscomp$1_elem$$=$$element_bottom$jscomp$1_elem$$.offset().top+$$element_bottom$jscomp$1_elem$$.outerHeight();var $scrollTop$$=$$$$(window).scrollTop();if($$element_bottom$jscomp$1_elem$$<$scrollTop$$)return!0;if(300<$$element_bottom$jscomp$1_elem$$-$scrollTop$$)return $me$$.$navi.find("li").removeClass("active"),$$$$(".m"+$idx$$).addClass("active"),
$me$$._imgAction($idx$$),!1})},_countDown:function(){(function($seconds$$){var $$timeArea$$=$$$$(".preregister"),$interval$$=setInterval(function(){if(0>=$seconds$$)return clearInterval($interval$$),$$timeArea$$.find(":first").hide(),$$timeArea$$.find(".preregister-countdown").html("\x3cdiv class\x3d'prereg-end'\x3e"+AL10N.Keyvisual.preeventClosed()+"\x3c/div\x3e"),!1;var $days$$=Math.floor($seconds$$/86400),$hours$$=Math.floor($seconds$$/3600)%24,$min$$=Math.floor($seconds$$/60)%60,$sec$$=$seconds$$%
60;$$$$(".preregister").is(":hidden")&&$$$$(".preregister").show();$$$$(".days").text($days$$);$$$$(".hours").text($hours$$);$$$$(".minutes").text($min$$);$$$$(".seconds").text($sec$$);$seconds$$--},1E3)})(Math.floor(((new Date(2022,2,23,23,59,59)).getTime()-(new Date).getTime())/1E3))},_linkBtn:function(){var $me$$=this;$$$$(".slide1 a").on("click",function(){var $top$$=$$$$("#section2").offset().top-$me$$.$headerHeight;$$$$("html, body").animate({scrollTop:$top$$},800)});$$$$(".slide2 a").on("click",
function(){var $top$$=$$$$("#section1").offset().top-$me$$.$headerHeight;$$$$("html, body").animate({scrollTop:$top$$},800)});$$$$(".slide5 .more").on("click",function(){var $top$$=$$$$("#section3").offset().top-$me$$.$headerHeight;$$$$("html, body").animate({scrollTop:$top$$},800)});$$$$(".faq-roadmap-link").on("click",function(){var $top$$=$$$$("#section4").offset().top-$me$$.$headerHeight;$$$$("html, body").animate({scrollTop:$top$$},800)});$$$$(".btn-detail-view").on("click",function(){$$$$(this).text($$$$(this).text()==
AL10N.Nft.btnOpen()?AL10N.Nft.btnClose():AL10N.Nft.btnOpen());$$$$(".card-minting-wrap").toggle()})},_imgAction:function($index$$){if(XLGames.isMobileView)return!1;$$$$(".section"+$index$$);1==$index$$&&$$$$(".car").stop().animate({right:"50%",opacity:"1"},1500)},_timeLine:function(){var $$timeline_block$$=$$$$(".direction");$$timeline_block$$.each(function(){$$$$(this).offset().top>$$$$(window).scrollTop()+.75*$$$$(window).height()&&$$$$(this).find(".flag, .desc, .desc-dim, .flag-ing").addClass("hidden")});
$$$$(window).on("scroll",function(){$$timeline_block$$.each(function(){$$$$(this).offset().top<=$$$$(window).scrollTop()+.75*$$$$(window).height()&&$$$$(this).find(".flag, .desc, .desc-dim, .flag-ing").hasClass("hidden")&&$$$$(this).find(".flag, .desc, .desc-dim, .flag-ing").removeClass("hidden").addClass("ani-on")})})},bindChangeLanguage:function(){$$$$(".text-lang").off("click");$$$$(".text-lang").on("click",function($e$$){$e$$.preventDefault();$e$$.stopPropagation();$$$$(".layer-lang").toggle()});
$$$$(".layer-lang").find("a").on("click",function($e$$){$e$$.preventDefault();location.href="/?lang\x3d"+$$$$(this).data("lang")})}})})(jQuery);